### ISSUE TITLE
Add currencies

### ISSUE THREAD

**Issue by jeanfrancis** [karask/bitcoinpos#1]
Would like to have XOF and XAF added

**Comment by karask** [comment]
I had XAF already but called it  "South African Franc" which was wrong. I now changed it to "South African Rand".

I have also added XOF.

The updated application is also published to play store as version 1.3.5. Let me know if there are any issues or you feel something is not precise (I am not very knowledgeable of Africa's currencies).

**Comment by jeanfrancis** [comment]
XAF and XOF are both for central and west africa , not related to south africa

**Comment by karask** [comment]
You are right of course. What I wrote above was wrong. The app has:

XAF - central
XOF - west
ZAR - south

Let me know if anything else is amiss.
